### ISSUE TITLE
IdentityResources and IdentityClaims

### ISSUE THREAD

**Issue by taslak** [IdentityServer/IdentityServer4.EntityFramework#42] opened 2016-12-06 08:20 UTC
Must all scopes be defined in table IdentityResources?

Get this error if scope is not defined in the IdentityResource table or no identityclaims is defined for scope.
Got this error even if i added data, so the sql run returned data.

IdentityServer4.Hosting.IdentityServerMiddleware|FATAL|Unhandled exception: System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Query.IIncludableQueryable`2<!!0,!!2> Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ThenInclude(Microsoft.EntityFrameworkCore.Query.IIncludableQueryable`2<!!0,System.Collections.Generic.ICollection`1<!!1>>, System.Linq.Expressions.Expression`1<System.Func`2<!!1,!!2>>)'.
   at IdentityServer4.EntityFramework.Stores.ResourceStore.FindApiResourcesByScopeAsync(IEnumerable`1 scopeNames)
   at IdentityServer4.Stores.IResourceStoreExtensions.<FindResourcesAsync>d__0.MoveNext()

Sql statements run (retrieved from log):
SELECT [identityResource].[Id], [identityResource].[Description], [identityResource].[DisplayName], [identityResource].[Emphasize], [identityResource].[Enabled], [identityResource].[Name], [identityResource].[Required], [identityResource].[ShowInDiscoveryDocument]
FROM [IdentityResources] AS [identityResource]
WHERE [identityResource].[Name] IN (N'internal')
ORDER BY [identityResource].[Id] 

Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory|INFO|  Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [i].[Id], [i].[IdentityResourceId], [i].[Type]
FROM [IdentityClaims] AS [i]
WHERE EXISTS (
    SELECT 1
    FROM [IdentityResources] AS [identityResource]
    WHERE [identityResource].[Name] IN (N'internal') AND ([i].[IdentityResourceId] = [identityResource].[Id]))

**Comment by scottbrady91** [comment] 2016-12-06 09:56
This is due to the use of .NET Core 1.1 which IdentityServer 4 does not currently support. Duplicate of #38, see this issue for more details.

**Closed by scottbrady91** 2016-12-06 09:56 UTC

**Comment by totht91** [comment] 2016-12-06 19:07
I think you are  supporting only 1.1 :)

https://github.com/IdentityServer/IdentityServer4/issues/529#issuecomment-265215856

**Comment by leastprivilege** [comment] 2016-12-06 19:17
We switched the main repo. All the others need to be migrated over.
