### ISSUE TITLE
Can't browse discovery with EF store in RC4-update1

### ISSUE THREAD

**Issue by ajtowf** [IdentityServer/IdentityServer4.EntityFramework#44] opened 2016-12-08 10:06 UTC
When using IdSrv4 with EF store (RC4-update1) the discovery document (/.well-known/openid-configuration) can't be browsed due to breaking changes in EF I'm guessing.

    MissingMethodException: Method not found: 
        'Microsoft.EntityFrameworkCore.Query.IIncludableQueryable`2<!!0,!!2>
 Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ThenInclude(Microsoft.EntityFrameworkCore.Query.IIncludableQueryable`2<!!0,System.Collections.Generic.ICollection`1<!!1>>, System.Linq.Expressions.Expression`1<System.Func`2<!!1,!!2>>)'.
IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResources()
IdentityServer4.Stores.IResourceStoreExtensions+<GetAllEnabledResourcesAsync>d__2.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by ajtowf** [comment] 2016-12-08 11:21
Tmp fix for this is to provide your own impl. of IResourceStore, copied the one from this repo and just changed all ThenInclude to Include.

**Comment by scottbrady91** [comment] 2016-12-08 11:24
Duplicate of #38. IdentityServer 4 is currently being migrated to support .NET 1.1 only.

**Closed by scottbrady91** 2016-12-08 11:24 UTC
